disabled_rules:

#    - trailing_whitespace

    - line_length
#    
#    - cyclomatic_complexity
#    
#    - vertical_parameter_alignment
#    
#    - function_body_length

    - force_cast
    
    - force_unwrapping
    
    - force_try
    
    - shorthand_operator
    
    - type_body_length
    
    - type_name
    
    - identifier_name

opt_in_rules:
    
included:

excluded:
