import Foundation

struct BattleDataModel: Codable {
    let id: Int
    let title, description, tip, image: String
    let missionContentList: [MissionContentList]
}

var missionMokData: [BattleDataModel] = [.init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")]),
                                         .init(id: 1,
                                               title: "게임1",
                                               description: "게임1설명",
                                               tip: "헤헤 알아서 잘 해보라구!",
                                               image: "",
                                               missionContentList: [.init(id: 1, content: "")])]
